src/BenefitsCodingChallenge/BenefitsCodingChallenge.WebApp/Controllers/BenefitsController.cs
#region Using

using System.Web.Mvc;

#endregion

namespace BenefitsCodingChallenge.WebApp.Controllers
{
    public class BenefitsController : Controller
    {
        // GET: Benefits
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/BenefitsCodingChallenge/BenefitsCodingChallenge.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><i class="fa fa-file-code-o"></i>&nbsp;Benefits Coding Challenge</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Dashboard", "Index", "Benefits")</li>
                <li>@Html.ActionLink("Employees", "Index", "Employees")</li>
                <li>@Html.ActionLink("Reports", "Index", "Reports")</li>
            </ul>
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)

</body>
</html>